### ISSUE TITLE
RuntimeError: Dimension Dismatch

### ISSUE THREAD

**Issue by Charlie0257** [columbia-ai-robotics/ASPiRe#1]
When I run the following command——
`python script/train_prior.py --d1 /home/charlie/PycharmProjects/ASPiRe/prior_data/maze_avoid_data/matrix_maze_avoid/ --d2 /home/charlie/PycharmProjects/ASPiRe/prior_data/maze_nav_data/maze2d-medium-dynamic-layout/ --log --kl_analytic --use_batch_norm --name PRIOR_NAME`

There is an error occurring——
`Traceback (most recent call last):`
  `File "script/train_prior.py", line 241, in <module>`
    `main()`
  `File "script/train_prior.py", line 192, in main`
    `sampler = sample_data(prior_data_source[prior_index])`
  `File "script/train_prior.py", line 139, in sample_data`
    `state_sample[i * EachSample_num:(i + 1) * EachSample_num] = torch.tensor(state[sample_index],`
`RuntimeError: The expanded size of the tensor (35) must match the existing size (37) at non-singleton dimension 1.  Target sizes: [20, 35].  Tensor sizes: [20, 37]`

Could you give me a demo of the command `python script/train_prior.py --d1 NAV_DATA_PATH --d2 AVOID_DATA_PATH --log --kl_analytic --use_batch_norm --name PRIOR_NAME`?

Thanks for any help :)

**Comment by mengdaxu** [comment]
Hi Charlie,

Could you please place the maze nav as d1 and maze avoid as d2?

**Comment by Charlie0257** [comment]
That suggestion makes the code work!
Thanks :)
